version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    environment:
      DATABASE_URL: postgres://tester:testpw@db:5432/bikematch

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: tester
      POSTGRES_PASSWORD: testpw
      POSTGRES_DB: bikematch
    ports:
      - "5434:5432"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tester -d bikematch"]
      interval: 10s
      timeout: 5s
      retries: 5
